### ISSUE TITLE
PKPApplication::getRequest() cannot be called statically

### ISSUE THREAD

**Issue by beausapach** [ojsde/openAIRE#10]
When trying to edit a section in a journal that has the OpenAIRE plugin installed we get an error in the browser windows: **"Failed Ajax request or invalid JSON returned"**.  

In the PHP logs we see:

**PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in /var/www/sites/esi/plugins/generic/openAIRE/OpenAIREPlugin.inc.php:102
#0 /var/www/sites/esi/lib/pkp/classes/plugins/HookRegistry.inc.php(107): OpenAIREPlugin->initDataSectionFormFields('sectionform::in...', Array)
  thrown in /var/www/sites/esi/plugins/generic/openAIRE/OpenAIREPlugin.inc.php on line 102**

Removing the plugin from the journal seems to resolve the issue.

We are currently running PHP 8.1.23 on Apache 2.4.6-99.

**Comment by ajnyga** [comment]
Hi, what version of OJS and the plugin are you seeing this?

**Comment by mpbraendle** [comment]
Hi @ajnyga - that error catches one with OJS 3.3 and PHP 8.0 . It can easily be remedied by replacing 
PKPApplication::getRequest() with PKPApplication::get()->getRequest()   or Application::get()->getRequest . There are several lines to fix:

```
grep -R getRequest *
OAIMetadataFormat_OpenAIRE.inc.php:		$request = Application::getRequest();
OpenAIREPlugin.inc.php:		$request = Application::getRequest();
OpenAIREPlugin.inc.php:		$request = Application::getRequest();
```

**Comment by jnugent** [comment]
Confirming that we are also seeing this in OJS 3.3, with the plugin up to date in the installation.

`
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in plugins/generic/openAIRE/OpenAIREPlugin.inc.php:102
`

**Comment by ctgraham** [comment]
A new `stable-3_3_0` branch based on https://github.com/ulsdevteam/openAIRE/commit/65bc3a6d0c7c5588a4d1dee4c7038c050a2cc2b0 would replace existing uses of `Application::getRequest()` with `Application::get()->getRequest()`.  Can we get this reviewed and released to the Plugin Gallery?

**Comment by ajnyga** [comment]
Sorry for taking so long with this, there is a new OpenAIRE coming from the CRAFT-OA project I have hoped to end up in the plugin gallery, but I am not sure when that is going to happen. So here is a new release with the fixes: https://github.com/ojsde/openAIRE/releases/tag/3.3.0.0

I will do a pr for gallery as well.
