### ISSUE TITLE
Error message with OpenAire

### ISSUE THREAD

**Issue by olkrueger** [ojsde/openAIRE#15]
Unfortunately, OpenAire issues some errors messages when you try to register the OAI with them. It's about the fields access level and project identifier. When asked, OpenAire told us that they have issues with the JATS transformation process from the OJS OpenAIRE plugin. They told us that they have just built a plugin for the OpenAIRE Guidelines v.4, which will be released in the next few weeks.   
Does anyone have any further information on this? Or similar experiences?

**Comment by ajnyga** [comment]
Hi, sorry for missing this comment earlier.
Yes, originally when this plugin was built, it was a request from OpenAIRE to use JATS for the output. However, the challenge was back then (and still is) that the OpenAIRE validation service does not support JATS. This was to my knowledge something they planned to change, but have not done that at least yet. That is why the plugin readme has a detailed instruction how to register you feed.

However, a new version of the OpenAIRE plugin has been built in the CRAFT-OA project. My goal in the near future is to make sure that this repository will replace the OpenAIRE plugin available in the PKP Plugin Gallery. When that happens, you should be able to install the new version from there. From the viewpoint of the editor not much should change, just that the registration process will work better and the new version complies the requirements better.
