### ISSUE TITLE
._ files in the plugin gallery package

### ISSUE THREAD

**Issue by mpbraendle** [ojsde/openAIRE#2]
The plugin gallery package contains ._ files (coming from the OS X virus scanner). Please remove them:

-rw-r--r--.  1 wwwadmin apache    49 Jan 14 09:35 .gitignore
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._.gitignore
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._index.php
-rw-r--r--.  1 wwwadmin apache   452 Jan 14 09:35 index.php
-rw-r--r--.  1 wwwadmin apache 35147 Jan 14 09:35 LICENSE
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._LICENSE
drwxr-xr-x.  4 wwwadmin apache    62 Jan 14 09:35 locale
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._locale
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._OAIMetadataFormat_OpenAIRE.inc.php
-rw-r--r--.  1 wwwadmin apache 17361 Jan 14 09:35 OAIMetadataFormat_OpenAIRE.inc.php
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._OAIMetadataFormatPlugin_OpenAIRE.inc.php
-rw-r--r--.  1 wwwadmin apache  1392 Jan 14 09:35 OAIMetadataFormatPlugin_OpenAIRE.inc.php
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._OpenAIREGatewayPlugin.inc.php
-rw-r--r--.  1 wwwadmin apache  2774 Jan 14 09:35 OpenAIREGatewayPlugin.inc.php
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._OpenAIREPlugin.inc.php
-rw-r--r--.  1 wwwadmin apache  6212 Jan 14 09:35 OpenAIREPlugin.inc.php
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._readme.md
-rw-r--r--.  1 wwwadmin apache  8349 Jan 14 09:35 readme.md
drwxr-xr-x.  3 wwwadmin apache    46 Jan 14 09:35 templates
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._templates
-rw-r--r--.  1 wwwadmin apache   222 Jan 14 09:35 ._version.xml
-rw-r--r--.  1 wwwadmin apache   572 Jan 14 09:35 version.xml

**Comment by ajnyga** [comment]
thanks, I will have a look.

**Comment by ajnyga** [comment]
weird that I can not see these although I usually see all hidden files, but added this in the gitignore file which will hopefully take care of the problem. Let me know if you still see them in the master branch.
