### ISSUE TITLE
Invalid XML file created

### ISSUE THREAD

**Issue by fdreger** [ojsde/openAIRE#6]
It seems that the plugin places all the tags in the default XML namespace. This is bad for two reasons:
- the JATS tags are defined in their own namespace; a valid parser cannot ignore the fact that the namespace is missing and will refuse to parse the tags;
- the OAI-PMH standard is explicit about the necessity of using the namespace in connection with format; quote: "every metadata part **must** include one or more xmlns prefixed attributes that define the correspondence between a metadata format prefix -- e.g. dc -- and the namespace URI (as defined by the XML namespace specification ) of the respective metadata format"

I think that correctness of the plugin calls for introducing a jats prefix (or openaire_jats, but it's more wordy) and associating it with the http://jats.nlm.nih.gov namespace (as declared).

**Comment by ajnyga** [comment]
thanks and sorry for missing this when you wrote it! I added the missing xmlns.

I looked through the other OJS oai plugins and it looks like that only dc uses prefixes. This is maybe something worth raising in the as a larger discussion?

**Comment by ajnyga** [comment]
also note here that in the CRAFT-OA project a new version of the plugin is being built and that is going to handle namespaces in more detail. Not part of that work myself but it will replace this plugin at some point. The basic functionalities will be the same though.
