### ISSUE TITLE
Invalid publication date?

### ISSUE THREAD

**Issue by fdreger** [ojsde/openAIRE#7]
Here's a front page of a journal https://czasopisma.bg.ug.edu.pl/index.php/arseducandi/issue/view/283

The page shows the editorial ("współpraca nierównych") as part of the 2019/16 issue.

The openaire_jats_plugin however claims it is published in 2021/01. Looking at the plugin output, there's no way to associate it with the 2019/16 issue, which is what we would consider "correct".

**Comment by ajnyga** [comment]
Hi, issues and articles have their own publication dates. Check the publication date of the editorial visible in the sidebar here: https://czasopisma.bg.ug.edu.pl/index.php/arseducandi/article/view/4533
